spring.application.name=spring-app-demo

management.endpoints.web.exposure.include = *
management.info.env.enabled = true

info.app.name=${spring.application.name}
info.app.description=Spring Boot Application Demo
info.app.version=1.0.0
