spring.application.name=spring-app-demo

management.endpoints.web.exposure.include = *

# How to exclude specific endpoints from being exposed over HTTP. By default, all endpoints are included.
# You can specify a comma-separated list of endpoint IDs to exclude.
# For example, to exclude the health and info endpoints, you would set the property like this:
#
# management.endpoints.web.exposure.exclude = health, info
management.info.env.enabled = true

info.app.name=${spring.application.name}
info.app.description=Spring Boot Application Demo
info.app.version=1.0.0


# spring.security.user.name=admin
# spring.security.user.password=admin123

#
# Define custom properties for the application
#
coach.name=John Doe
team.name=Spring Boot Team

# How you can configure some of the Spring application properties, such as the server port, context path, and logging level.
server.port=8585
server.servlet.context-path=/mycoolapi
